;CONSTANTS    Delha1    DATA    -9999    ;    enthalpy (acid diss. 1)                        (J/mol)    name of parameters used ---->
;CONSTANTS    Delha2    DATA    -9999    ;    enthalpy (acid diss. 2)                        (J/mol)    name of parameters used ---->
;CONSTANTS    Delhac    DATA    -9999    ;    enthalpy  (acid catalysed hydrolysis)         (J/mol)    name of parameters used ---->
;CONSTANTS    Delhb1    DATA    -9999    ;    enthalpy (base diss. 1)                        (J/mol)    name of parameters used ---->
;CONSTANTS    Delhb2    DATA    -9999    ;    enthalpy (base diss. 2)                        (J/mol)    name of parameters used ---->
;CONSTANTS    Delhba    DATA    -9999    ;    enthalpy  (base catalysed hydrolysis)          (J/mol)    name of parameters used ---->
;CONSTANTS    Delhn    DATA    -9999    ;    enthalpy  (neutral hydrolysis)                 (J/mol)    name of parameters used ---->
;CONSTANTS    Delho    DATA    -9999    ;    default reaction enthalpy                      (J/mol)    name of parameters used ---->
;CONSTANTS    Delhp    DATA    -9999    ;    enthalpy  (photolysis)                         (J/mol)    name of parameters used ---->
;CONSTANTS    Delhs    DATA    -9999    ;    enthalpy (water solubility)                    (J/mol)    name of parameters used ---->
CONSTANTS    MolMass    DATA    288.39    ;    Molar mass                                     (g/mol)    name of parameters used ---->    none
;CONSTANTS    X1sedim    DATA    -9999    ;    Karickhoff par. POC aquatic sediments              (-)    name of parameters used ---->
;CONSTANTS    X1soil    DATA    -9999    ;    Karickhoff par. POC soil and groundw comp         (-)    name of parameters used ---->
;CONSTANTS    X1water    DATA    -9999    ;    Karickhoff par. POC water comp.                    (-)    name of parameters used ---->
;CONSTANTS    X2sedim    DATA    -9999    ;     Karickhoff par. DOC aquatic sediments               (-)    name of parameters used ---->
;CONSTANTS    X2soil    DATA    -9999    ;    Karickhoff par. DOC soil and groundw comp         (-)    name of parameters used ---->
;CONSTANTS    X2water    DATA    -9999    ;    Karickhoff par. DOC water comp.                    (-)    name of parameters used ---->
CONSTANTS    bp    DATA    974.9966666666668    ;    boiling point                                      (C)    name of parameters used ---->    Fragment
model suite    MPBPWIN v1.43: Adaption of the Stein & Brown fragment model)    Undisclosed
CONSTANTS    dhaw    DATA    138560.0    ;    enthalpy of phase change a-w                   (J/mol)    name of parameters used ---->    dhaw
;CONSTANTS    dhoa    DATA    -9999    ;    enthalpy of phase change o-a                   (J/mol)    name of parameters used ---->
;CONSTANTS    dhow    DATA    -9999    ;    enthalpy of phase change o-w                   (J/mol)    name of parameters used ---->
;CONSTANTS    kac    DATA    -9999    ;    acid catalysed hydrolysis rate constant          (1/s)    name of parameters used ---->
CONSTANTS    kaw0    DATA    -12.6324012029333    ;    log10 Part coeff air water at ref T                (-)    name of parameters used ---->    Unpublished fragments    Best of literature fragment models    Unpublished LSER (UFZ)    HenryWin 3.20 (bond model)
;CONSTANTS    kba    DATA    -9999    ;    base catalysed hydrolysis rate constant          (1/s)    name of parameters used ---->
CONSTANTS    kde    DATA    3.5007429292929294e-07    ;    half-life l degradation rate in soil             (1/s)    name of parameters used ---->
CONSTANTS    kds    DATA    1.1325933006535949e-07    ;    half-life degradation rate in sediment           (1/s)    name of parameters used ---->    Kühne R     Ebert R-U     Schüürmann G 2007. Estimation of compartmental half-lives of organic compounds - structural similarity versus EPI-Suite. QSAR Comb. Sci. 26: 542-549. 
CONSTANTS    kdw    DATA    1.1325933006535948e-06    ;    half-life degradation rate in water              (1/s)    name of parameters used ---->
;CONSTANTS    kn    DATA    -9999    ;    neutral hydrolysis rate constant                 (1/s)    name of parameters used ---->
CONSTANTS    koa0    DATA    15.958    ;    log10 Part coeff octanol air at ref T              (-)    name of parameters used ---->    log Koa
CONSTANTS    kow0    DATA    2.7005999999999997    ;    log10 Part coeff octanol water at ref T           (-)    name of parameters used ---->    Consensus model (fragments)    Read-across    KOWWIN 1.68    Undisclosed fragments    Undisclosed similarity based    Consensus
;CONSTANTS    kp    DATA    -9999    ;    direct photolysis rate at surface                (1/s)    name of parameters used ---->
