CONSTANTS    Degredation rate in sediment    DATA    1.13259330065e-08    ;    NA    1/s    name of parameters used ---->    HL in sediment    Kühne R     Ebert R-U     Schüürmann G 2007. Estimation of compartmental half-lives of organic compounds - structural similarity versus EPI-Suite. QSAR Comb. Sci. 26: 542-549. 
CONSTANTS    Degredation rate in soil    DATA    3.50074292929e-08    ;    NA    1/s    name of parameters used ---->    HL in soil    NA
CONSTANTS    Degredation rate in water    DATA    1.13259330065e-07    ;    NA    1/s    name of parameters used ---->    HL in water    NA
CONSTANTS    Koc    DATA    -9999    ;    NA    L/kg    name of parameters used ---->
CONSTANTS    Vapor pressure    DATA    4.17229e-12    ;    NA    Pa    name of parameters used ---->    Vp    MPBPWIN v1.43: Grain modified Antoine model and Mackay model    Vp    Undisclosed model
CONSTANTS    Water solubility    DATA    0.00383813226881    ;    NA    mol/L    name of parameters used ---->    Sw    Unpublished commercial fragment model     Ks    WSKOW v1.42 (based on  Kow)
CONSTANTS    log Kow    DATA    4.27    ;    NA    -    name of parameters used ---->    log Kow    KOWWIN 1.68    log Kow    Undisclosed fragments    log Kow    Undisclosed similarity based    log Kow    Consensus
CONSTANTS    pka1    DATA    4.35    ;    NA    -    name of parameters used ---->    pKa1    Undisclosed commercial models
CONSTANTS    pka2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb2    DATA    -9999    ;    NA    -    name of parameters used ---->
