CONSTANTS    Degredation rate in sediment    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Degredation rate in soil    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Degredation rate in water    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Koc    DATA    11820.0    ;    NA    L/kg    name of parameters used ---->    Koc (MCI)
CONSTANTS    Vapor pressure    DATA    1.08e-27    ;    NA    Pa    name of parameters used ---->    Vapor Pressure (Antoine Method)
CONSTANTS    Water solubility    DATA    2.6571    ;    NA    mol/L    name of parameters used ---->    Water Solubility
CONSTANTS    log Kow    DATA    2.76    ;    NA    -    name of parameters used ---->    log Kow
CONSTANTS    pka1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pka2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS Delho  DATA    30000