CONSTANTS    Degredation rate in sediment    DATA    3.5007429292929296e-08    ;    NA    1/s    name of parameters used ---->    HL in sed [h]
CONSTANTS    Degredation rate in soil    DATA    1.1325933006535949e-07    ;    NA    1/s    name of parameters used ---->    HL in soil [h]
CONSTANTS    Degredation rate in water    DATA    3.5007429292929294e-07    ;    NA    1/s    name of parameters used ---->    HL in water [h]
CONSTANTS    Koc    DATA    -9999    ;    NA    L/kg    name of parameters used ---->
CONSTANTS    Vapor pressure    DATA    -9999    ;    NA    Pa    name of parameters used ---->
CONSTANTS    Water solubility    DATA    -9999    ;    NA    mol/L    name of parameters used ---->
CONSTANTS    log Kow    DATA    4.1458    ;    NA    -    name of parameters used ---->    log Kow
CONSTANTS    pka1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pka2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS Delho  DATA    30000