CONSTANTS    Degredation rate in sediment    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Degredation rate in soil    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Degredation rate in water    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Koc    DATA    -9999    ;    NA    L/kg    name of parameters used ---->
CONSTANTS    Vapor pressure    DATA    -9999    ;    NA    Pa    name of parameters used ---->
CONSTANTS    Water solubility    DATA    -9999    ;    NA    mol/L    name of parameters used ---->
CONSTANTS    log Kow    DATA    0.2888    ;    NA    -    name of parameters used ---->    Koc (Log Kow)
CONSTANTS    pka1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pka2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS Delho  DATA    30000