CONSTANTS    Degredation rate in sediment    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Degredation rate in soil    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Degredation rate in water    DATA    -9999    ;    NA    1/s    name of parameters used ---->
CONSTANTS    Koc    DATA    29.37    ;    NA    L/kg    name of parameters used ---->    Koc (MCI)
CONSTANTS    Vapor pressure    DATA    0.66395    ;    NA    Pa    name of parameters used ---->    Vapor Pressure (Antoine Method)
CONSTANTS    Water solubility    DATA    1486.3    ;    NA    mol/L    name of parameters used ---->    Water Solubility
CONSTANTS    log Kow    DATA    3.0    ;    NA    -    name of parameters used ---->    log Kow
CONSTANTS    pka1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pka2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS Delho  DATA    30000