CONSTANTS    Delha1    DATA    -9999    ;    enthalpy (acid diss. 1)                        (J/mol)    SU    name of parameters used ---->
CONSTANTS    Delha2    DATA    -9999    ;    enthalpy (acid diss. 2)                        (J/mol)    SU    name of parameters used ---->
CONSTANTS    Delhac    DATA    -9999    ;    enthalpy  (acid catalysed hydrolysis)         (J/mol)    LMC and UFZ    name of parameters used ---->
CONSTANTS    Delhb1    DATA    -9999    ;    enthalpy (base diss. 1)                        (J/mol)    SU    name of parameters used ---->
CONSTANTS    Delhb2    DATA    -9999    ;    enthalpy (base diss. 2)                        (J/mol)    SU    name of parameters used ---->
CONSTANTS    Delhba    DATA    -9999    ;    enthalpy  (base catalysed hydrolysis)          (J/mol)    LMC and UFZ    name of parameters used ---->
CONSTANTS    Delhn    DATA    -9999    ;    enthalpy  (neutral hydrolysis)                 (J/mol)    LMC and UFZ    name of parameters used ---->
CONSTANTS    Delho    DATA    -9999    ;    default reaction enthalpy                      (J/mol)    SU    name of parameters used ---->
CONSTANTS    Delhp    DATA    -9999    ;    enthalpy  (photolysis)                         (J/mol)    SU    name of parameters used ---->
CONSTANTS    Delhs    DATA    -9999    ;    enthalpy (water solubility)                    (J/mol)    SU    name of parameters used ---->
CONSTANTS    MolMass    DATA    -9999    ;    Molar mass                                     (g/mol)    UFZ    name of parameters used ---->
CONSTANTS    X1sedim    DATA    -9999    ;    Karickhoff par. POC aquatic sediments              (-)    SU    name of parameters used ---->
CONSTANTS    X1soil    DATA    -9999    ;    Karickhoff par. POC soil and groundw comp         (-)    SU    name of parameters used ---->
CONSTANTS    X1water    DATA    -9999    ;    Karickhoff par. POC water comp.                    (-)    SU    name of parameters used ---->
CONSTANTS    X2sedim    DATA    -9999    ;     Karickhoff par. DOC aquatic sediments               (-)    SU    name of parameters used ---->
CONSTANTS    X2soil    DATA    -9999    ;    Karickhoff par. DOC soil and groundw comp         (-)    SU    name of parameters used ---->
CONSTANTS    X2water    DATA    -9999    ;    Karickhoff par. DOC water comp.                    (-)    SU    name of parameters used ---->
CONSTANTS    bp    DATA    -9999    ;    boiling point                                      (C)    LMC    name of parameters used ---->
CONSTANTS    dhaw    DATA    -9999    ;    enthalpy of phase change a-w                   (J/mol)    UFZ    name of parameters used ---->
CONSTANTS    dhoa    DATA    -9999    ;    enthalpy of phase change o-a                   (J/mol)    SU    name of parameters used ---->
CONSTANTS    dhow    DATA    -9999    ;    enthalpy of phase change o-w                   (J/mol)    SU    name of parameters used ---->
CONSTANTS    kac    DATA    -9999    ;    acid catalysed hydrolysis rate constant          (1/s)    LMC and UFZ    name of parameters used ---->
CONSTANTS    kaw0    DATA    -9999    ;    log10 Part coeff air water at ref T                (-)    UFZ    name of parameters used ---->
CONSTANTS    kba    DATA    -9999    ;    base catalysed hydrolysis rate constant          (1/s)    LMC and UFZ    name of parameters used ---->
CONSTANTS    kde    DATA    5.014084924768519e-07    ;    half-life l degradation rate in soil             (1/s)    LMC    name of parameters used ---->    Ultimate Half Life Predicted
CONSTANTS    kds    DATA    5.014084924768519e-07    ;    half-life degradation rate in sediment           (1/s)    LMC    name of parameters used ---->    Ultimate Half Life Predicted
CONSTANTS    kdw    DATA    5.014084924768519e-07    ;    half-life degradation rate in water              (1/s)    LMC    name of parameters used ---->    Ultimate Half Life Predicted
CONSTANTS    kn    DATA    -9999    ;    neutral hydrolysis rate constant                 (1/s)    LMC and UFZ    name of parameters used ---->
CONSTANTS    koa0    DATA    -9999    ;    log10 Part coeff octanol air at ref T              (-)    UFZ    name of parameters used ---->
CONSTANTS    kow0    DATA    -9999    ;    log10 Part coeff octanol water at ref T           (-)    UFZ    name of parameters used ---->
CONSTANTS    kp    DATA    -9999    ;    direct photolysis rate at surface                (1/s)    SU    name of parameters used ---->
CONSTANTS    ks    DATA    -9999    ;    water solubility                              (mol/m3)    UFZ    name of parameters used ---->
CONSTANTS    mp    DATA    -9999    ;    melting point                                      (C)    LMC    name of parameters used ---->
CONSTANTS    pka1    DATA    -9999    ;    -log 10 acid dissociation constant 1               (-)    UFZ    name of parameters used ---->
CONSTANTS    pka2    DATA    -9999    ;    -log 10acid dissociation constant 2                (-)    UFZ    name of parameters used ---->
CONSTANTS    pkb1    DATA    -9999    ;    -log10 base dissociation constant 1                (-)    UFZ    name of parameters used ---->
CONSTANTS    pkb2    DATA    -9999    ;    - log10 base dissociation constant 2               (-)    UFZ    name of parameters used ---->
CONSTANTS    pv    DATA    -9999    ;    vapour pressure                                   (Pa)    UFZ    name of parameters used ---->
CONSTANTS    toa1    DATA    25.0    ;    ref.temp.(acid diss. constant 1)                   (C)    UFZ    name of parameters used ---->
CONSTANTS    toa2    DATA    25.0    ;    ref.temp.(acid diss. constant 2)                   (C)    UFZ    name of parameters used ---->
CONSTANTS    toac    DATA    25.0    ;    ref.temp. (acid catalysed hydrolysis k)           (C)    LMC and UFZ    name of parameters used ---->
CONSTANTS    tob1    DATA    25.0    ;    ref.temp.(base diss. constant 1)                   (C)    UFZ    name of parameters used ---->
CONSTANTS    tob2    DATA    25.0    ;    ref.temp.(base diss. constant 2)                   (C)    UFZ    name of parameters used ---->
CONSTANTS    toba    DATA    25.0    ;    ref.temp. (base catalysed hydrolysis k)            (C)    LMC and UFZ    name of parameters used ---->
CONSTANTS    tode    DATA    25.0    ;    ref.temp. (mic. deg. soil k)                      (C)    LMC    name of parameters used ---->
CONSTANTS    tods    DATA    25.0    ;    ref.temp. (mic. deg. sediment k)                  (C)    LMC    name of parameters used ---->
CONSTANTS    todw    DATA    25.0    ;    ref.temp. (mic. deg. water k)                      (C)    LMC    name of parameters used ---->
CONSTANTS    ton    DATA    25.0    ;    ref.temp. (neutral hydrolysis k)                   (C)    LMC and UFZ    name of parameters used ---->
CONSTANTS    top    DATA    25.0    ;    ref.temp. (photolysis k)                           (C)    SU    name of parameters used ---->
CONSTANTS    tos    DATA    25.0    ;    ref.temp.(water solubility k)                      (C)    UFZ    name of parameters used ---->
CONSTANTS Delho  DATA    30000