CONSTANTS    Degredation rate in sediment    DATA    1.13259330065e-07    ;    NA    1/s    name of parameters used ---->    HL in sediment    Kühne R     Ebert R-U     Schüürmann G 2007. Estimation of compartmental half-lives of organic compounds - structural similarity versus EPI-Suite. QSAR Comb. Sci. 26: 542-549. 
CONSTANTS    Degredation rate in soil    DATA    3.50074292929e-07    ;    NA    1/s    name of parameters used ---->    HL in soil    NA
CONSTANTS    Degredation rate in water    DATA    3.50074292929e-07    ;    NA    1/s    name of parameters used ---->    HL in water    NA
CONSTANTS    Koc    DATA    -9999    ;    NA    L/kg    name of parameters used ---->
CONSTANTS    Vapor pressure    DATA    33541.6125    ;    NA    Pa    name of parameters used ---->    Vp    Grain CF 1990. Vapor pressure. In: Lyman WJ     Reehl WF     Rosenblatt DH (eds)  Handbook of Chemical Property Estimation Methods. (3rd edition) American Chemical Society     Washington (DC     USA). Chapter 14     pp. 14-1 - 14-20. (Antoine based version)    Vp    Read-across    Vp    MPBPWIN v1.43: Grain modified Antoine model and Mackay model    Vp    Undisclosed model
CONSTANTS    Water solubility    DATA    0.225    ;    NA    mol/L    name of parameters used ---->    Sw    Kühne R     Ebert R-U     Schüürmann G 2006. Model selection based on structural similarity – method description and application to water solubility prediction. J. Chem. Inf. Model. 46: 636-641.    Sw    Unpublished commercial fragment model     Ks    WSKOW v1.42 (based on  Kow)
CONSTANTS    log Kow    DATA    1.365    ;    NA    -    name of parameters used ---->    log Kow    Consensus model (fragments)    log Kow    Read-across    log Kow    KOWWIN 1.68    log Kow    Undisclosed fragments    log Kow    Undisclosed similarity based    log Kow    Consensus
CONSTANTS    pka1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pka2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb2    DATA    -9999    ;    NA    -    name of parameters used ---->
