CONSTANTS    Degredation rate in sediment    DATA    3.5007429292929294e-09    ;    NA    1/s    name of parameters used ---->    HL in sed [h]
CONSTANTS    Degredation rate in soil    DATA    3.5007429292929294e-09    ;    NA    1/s    name of parameters used ---->    HL in soil [h]
CONSTANTS    Degredation rate in water    DATA    1.1325933006535949e-07    ;    NA    1/s    name of parameters used ---->    HL in water [h]
CONSTANTS    Koc    DATA    695200.0    ;    NA    L/kg    name of parameters used ---->    Koc (MCI)
CONSTANTS    Vapor pressure    DATA    8.7726e-08    ;    NA    Pa    name of parameters used ---->    Vapor Pressure (Antoine Method)
CONSTANTS    Water solubility    DATA    6.7673e-08    ;    NA    mol/L    name of parameters used ---->    Water Solubility
CONSTANTS    log Kow    DATA    8.2093    ;    NA    -    name of parameters used ---->    log Kow    log Kow
CONSTANTS    pka1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pka2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb1    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS    pkb2    DATA    -9999    ;    NA    -    name of parameters used ---->
CONSTANTS Delho  DATA    30000