CONSTANTS    Degredation rate in sediment    DATA    1.13259330065e-07    ;    NA    1/s    name of parameters used ---->    HL in sediment    Kühne R     Ebert R-U     Schüürmann G 2007. Estimation of compartmental half-lives of organic compounds - structural similarity versus EPI-Suite. QSAR Comb. Sci. 26: 542-549. 
CONSTANTS    Degredation rate in soil    DATA    1.13259330065e-06    ;    NA    1/s    name of parameters used ---->    HL in soil    NA
CONSTANTS    Degredation rate in water    DATA    1.13259330065e-06    ;    NA    1/s    name of parameters used ---->    HL in water    NA
CONSTANTS    Koc    DATA    -9999    ;    NA    L/kg    name of parameters used ---->
CONSTANTS    Vapor pressure    DATA    3.09256e-23    ;    NA    Pa    name of parameters used ---->    Vp    MPBPWIN v1.43: Grain modified Antoine model and Mackay model    Vp    Undisclosed model
CONSTANTS    Water solubility    DATA    1.02374426782e-06    ;    NA    mol/L    name of parameters used ---->    Sw    Kühne R     Ebert R-U     Schüürmann G 2006. Model selection based on structural similarity – method description and application to water solubility prediction. J. Chem. Inf. Model. 46: 636-641.    Sw    Unpublished commercial fragment model     Ks    WSKOW v1.42 (based on  Kow)
CONSTANTS    log Kow    DATA    3.14    ;    NA    -    name of parameters used ---->    log Kow    Consensus model (fragments)    log Kow    Read-across    log Kow    KOWWIN 1.68    log Kow    Undisclosed fragments    log Kow    Undisclosed similarity based    log Kow    Consensus
CONSTANTS    pka1    DATA    12.7    ;    NA    -    name of parameters used ---->    pKa1    Undisclosed commercial models
CONSTANTS    pka2    DATA    13.26    ;    NA    -    name of parameters used ---->    pKa2    
CONSTANTS    pkb1    DATA    5.45    ;    NA    -    name of parameters used ---->    pKb1    
CONSTANTS    pkb2    DATA    -9999    ;    NA    -    name of parameters used ---->
